apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: test-project

namespace: test1
nameSuffix: -test1

resources:
- configmap.yaml
- deployment.yaml
- nginx-service.yaml
- ingress.yaml
