apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: test-project

namespace: default
nameSuffix: -default

resources:
- configmap.yaml
- deployment.yaml
- nginx-service.yaml
- ingress.yaml
